{{- if .Values.removeStorageClassJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "ebs.name" . }}-remove-sc-job
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    app.kubernetes.io/component: {{ template "ebs.name" . }}-remove-sc-job
    {{- include "labels.common" . | nindent 4 }}
rules:
- apiGroups: 
  - storage.k8s.io
  resources: 
  - storageclasses
  verbs: 
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "ebs.name" . }}-remove-sc-job
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    app.kubernetes.io/component: {{ template "ebs.name" . }}-remove-sc-job
    {{- include "labels.common" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "ebs.name" . }}-remove-sc-job
subjects:
  - kind: ServiceAccount
    name: {{ template "ebs.name" . }}-remove-sc-job
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
