{{- if .Values.enableVolumeSnapshot }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ebs.name.crdInstall" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app.kubernetes.io/component: "{{ template "ebs.name.crdInstall" . }}"
    {{- include "labels.common" . | nindent 4 }}
    role: "{{ template "ebs.CRDInstallSelector" . }}"
{{- end }}