apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./external-snapshotter-upstream/deploy/kubernetes/snapshot-controller
  - ./external-snapshotter-upstream/client/config/crd

labels:
  - pairs:
      application.giantswarm.io/team: "phoenix"
      giantswarm.io/service-type: "managed"
    includeTemplates: true

images:
  - name: registry.k8s.io/sig-storage/snapshot-controller
    newName: gsoci.azurecr.io/giantswarm/snapshot-controller

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: add
        path: /metadata/annotations/helm.sh~1resource-policy
        value: keep
