apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./external-snapshotter-upstream/deploy/kubernetes/snapshot-controller
  - ./external-snapshotter-upstream/client/config/crd

labels:
  - pairs:
      application.giantswarm.io/team: "phoenix"
      giantswarm.io/service-type: "managed"
    includeTemplates: true

images:
  - name: registry.k8s.io/sig-storage/snapshot-controller
    newName: gsoci.azurecr.io/giantswarm/snapshot-controller

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: add
        path: /metadata/annotations/helm.sh~1resource-policy
        value: keep
  - target:
      kind: ServiceAccount
      name: snapshot-controller
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          eks.amazonaws.com/role-arn: '{{ .Values.clusterID }}-ebs-csi-driver-role'
  - target:
      kind: Deployment
      name: snapshot-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: snapshot-controller
      spec:
        template:
          spec:
            securityContext:
              runAsNonRoot: true
              runAsUser: 65534
              runAsGroup: 65534
              seccompProfile:
                type: RuntimeDefault
            containers:
              - name: snapshot-controller
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  runAsNonRoot: true
                  runAsUser: 65534
                  runAsGroup: 65534
                  readOnlyRootFilesystem: true
                  seccompProfile:
                    type: RuntimeDefault
