apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./external-snapshotter-upstream/client/config/crd

labels:
  - pairs:
      application.giantswarm.io/team: "phoenix"
      giantswarm.io/service-type: "managed"
    includeTemplates: true

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: add
        path: /metadata/annotations/helm.sh~1resource-policy
        value: keep
