apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/aws-ebs-csi-driver-app/templates
  contents:
  - path: .
    git:
      url: https://github.com/giantswarm/aws-ebs-csi-driver-upstream
      ref: master
      depth: 1
    newRootPath: charts/aws-ebs-csi-driver/templates
- path: vendor
  contents:
  - path: external-snapshotter
    git:
      url: https://github.com/kubernetes-csi/external-snapshotter
      ref: master
      depth: 1
    includePaths:
    - deploy/kubernetes/**/*
    - client/config/crd/**/*
    ignorePaths:
    - .gitignore
    - kustomization.yaml
