---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ebs-csi-controller
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules: {{ if .Values.global.podSecurityStandards.enforced }}[]{{ else }}
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - ebs-csi-controller
  verbs:
  - use
{{- end }}
