---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ebs-csi-node
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - ebs-csi-node
  verbs:
  - use
{{- if .Values.enableVolumeLimit }}
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - patch
{{ end }}