---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebs-csi-controller-binding
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: ebs-csi-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ebs-csi-controller
  apiGroup: rbac.authorization.k8s.io
