apiVersion: v1
kind: Service
metadata:
  name: ebs-csi-controller
  namespace: kube-system
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.controller.httpEndpoint }}
  selector:
    app: ebs-csi-controller
