apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ebs-csi-controller
  namespace: kube-system
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app: ebs-csi-controller
