apiVersion: policy.giantswarm.io/v1alpha1
kind: PolicyException
metadata:
  name: ebs-csi-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
spec:
  policies:
    - disallow-host-path
    - disallow-privileged-containers
    - restrict-volume-types
    - disallow-privilege-escalation
    - require-run-as-non-root-user
    - require-run-as-nonroot
    - restrict-seccomp-strict
  targets:
    - kind: DaemonSet
      namespaces:
      - kube-system
      names:
      - ebs-csi-node*
    - kind: Pod
      namespaces:
      - kube-system
      names:
      - ebs-csi-node*
