apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: ebs-csi-node
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  runAsUser:
    ranges:
    - max: 65535
      min: 1000
    rule: MustRunAs
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  hostPorts:
  - min: 9808
    max: 9808
  volumes:
  - secret
  - configMap
  - hostPath
