apiVersion: v1
kind: Service
metadata:
  name: ebs-csi-controller
  namespace: kube-system
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: {{ .Values.controller.httpEndpoint }}
spec:
  ports:
  - port: {{ .Values.controller.httpEndpoint }}
  selector:
    {{- include "labels.selector" . | nindent 4 }}