apiVersion: v1
kind: Service
metadata:
  name: ebs-csi-controller
  namespace: kube-system
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  annotations:
    giantswarm.io/monitoring-port: "{{ .Values.controller.httpEndpoint }}"
spec:
  ports:
  - port: {{ .Values.controller.httpEndpoint }}
  selector:
    app: ebs-csi-controller
