{{- if .Values.enableVolumeSnapshot }}
{{ if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" }}
{{ if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ebs-snapshot-controller
  namespace: kube-system
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: snapshot-controller
      controlledValues: RequestsAndLimits
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  ebs-snapshot-controller
  updatePolicy:
    updateMode: Auto
{{ end }}
{{ end }}
{{ end }}
