{{- if .Values.enableVolumeSnapshot }}
#Snapshot controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-snapshot-controller
  namespace: kube-system
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: ebs-snapshot-controller
  # the snapshot controller won't be marked as ready if the v1 CRDs are unavailable
  # in #504 the snapshot-controller will exit after around 7.5 seconds if it
  # can't find the v1 CRDs so this value should be greater than that
  minReadySeconds: 15
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        app: ebs-snapshot-controller
        {{- include "labels.common" . | nindent 8 }}
        {{- if .Values.snapshotController.podLabels }}
        {{- toYaml .Values.snapshotController.podLabels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: ebs-snapshot-controller
      nodeSelector:
        kubernetes.io/os: linux
        {{- with .Values.nodeSelector }}
{{ toYaml . | indent 8 }}
        {{- end }}
      priorityClassName: {{ .Values.priorityClassName | default "system-cluster-critical" }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
        {{- if .Values.tolerateAllTaints }}
        - operator: Exists
        {{- else }}
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        {{- end }}
        {{- with .Values.tolerations }}
{{ toYaml . | indent 8 }}
        {{- end }}
      containers:
        - name: snapshot-controller
          image: {{ printf "%s/%s:%s" .Values.global.image.registry .Values.snapshotController.repository .Values.snapshotController.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          args:
            - --v={{ .Values.controller.logLevel }}
            - --leader-election=true
{{- end }}
