{{- if .Values.enableVolumeSnapshot }}
#Snapshot controller
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ebs-snapshot-controller
  namespace: kube-system
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ebs-snapshot-controller
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        app: ebs-snapshot-controller
        {{- include "labels.common" . | nindent 8 }}
        {{- if .Values.snapshotController.podLabels }}
        {{- toYaml .Values.snapshotController.podLabels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: ebs-snapshot-controller
      nodeSelector:
        kubernetes.io/os: linux
        {{- with .Values.nodeSelector }}
{{ toYaml . | indent 8 }}
        {{- end }}
      priorityClassName: {{ .Values.priorityClassName | default "system-cluster-critical" }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
        {{- if .Values.tolerateAllTaints }}
        - operator: Exists
        {{- else }}
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        {{- end }}
        {{- with .Values.tolerations }}
{{ toYaml . | indent 8 }}
        {{- end }}
      containers:
        - name: snapshot-controller
          image: {{ printf "%s/%s:%s" .Values.global.image.registry .Values.snapshotController.repository .Values.snapshotController.tag }}
          imagePullPolicy: IfNotPresent
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          args:
            - --v={{ .Values.controller.logLevel }}
            - --leader-election=false
{{- end }}
