kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-csi
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: {{ .Values.enableVolumeScheduling }}
reclaimPolicy: Delete
parameters:
  type: gp2
  encrypted: "true"
