# Default values for aws-ebs-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: aws-ebs-csi-driver

replicaCount: 1

image:
  repository: docker.io/giantswarm/aws-ebs-csi-driver
  tag: "v1.3.0"
  pullPolicy: IfNotPresent

init:
  repository: docker.io/giantswarm/aws-ebs-csi-volume-limiter
  tag: "0.1.0"
  pullPolicy: IfNotPresent

sidecars:
  provisionerImage:
    repository: docker.io/giantswarm/csi-provisioner
    tag: "v3.0.0"
  attacherImage:
    repository: docker.io/giantswarm/csi-attacher
    tag: "v3.3.0"
  snapshotterImage:
    repository: docker.io/giantswarm/csi-snapshotter
    tag: "v4.2.1"
  livenessProbeImage:
    repository: docker.io/giantswarm/livenessprobe
    tag: "v2.4.0"
  resizerImage:
    repository: docker.io/giantswarm/csi-resizer
    tag: "v1.3.0"
  nodeDriverRegistrarImage:
    repository: docker.io/giantswarm/csi-node-driver-registrar
    tag: "v2.3.0"

snapshotController:
  repository: docker.io/giantswarm/snapshot-controller
  tag: "v4.2.1"
  podAnnotations: {}
  podLabels: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

# True if enable ebs volume limits per instance type
enableVolumeLimit: true

# True if enable volume scheduling for dynamic volume provisioning
enableVolumeScheduling: true

# True if enable volume snapshot
enableVolumeSnapshot: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

priorityClassName: ""
nodeSelector: {}
tolerateAllTaints: true
tolerations: []
affinity: {}

# TSCs without the label selector stanza
#
# Example:
#
# topologySpreadConstraints:
#  - maxSkew: 1
#    topologyKey: topology.kubernetes.io/zone
#    whenUnsatisfiable: ScheduleAnyway
#  - maxSkew: 1
#    topologyKey: kubernetes.io/hostname
#    whenUnsatisfiable: ScheduleAnyway

topologySpreadConstraints: []

# Extra volume tags to attach to each dynamically provisioned volume.
# ---
# extraVolumeTags:
#   key1: value1
#   key2: value2
extraVolumeTags: {}

# If set, add pv/pvc metadata to plugin create requests as parameters.
extraCreateMetadata: true

# clusterID is dynamic environment value, calculated after cluster creation
# applies only to Giant Swarm clusters
clusterID: "test-cluster"

# AWS region to use. If not specified then the region will be looked up via the AWS EC2 metadata
# service.
# ---
# region: us-east-1
region: ""

# Additonal environment variables for the controller
controller:
  httpEndpoint: ""
  extraVars: {}
  logLevel: 2

node:
  priorityClassName: ""
  nodeSelector: {}
  podAnnotations: {}
  tolerateAllTaints: false
  tolerations: []
  resources: {}
  logLevel: 2

serviceAccount:
  controller:
    annotations: {}
  snapshot:
    annotations: {}

global:
  image:
    registry: docker.io
  securityContext:
    # global.securityContext.groupID
    groupID: 1000
    # global.securityContext.userID
    userID: 1000
    # global.securityContext.runAsNonRoot
    runAsNonRoot: true
