# Default values for aws-ebs-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: aws-ebs-csi-driver

replicaCount: 1

image:
  repository: quay.io/giantswarm/aws-ebs-csi-driver
  tag: "v0.9.0"
  pullPolicy: IfNotPresent

init:
  repository: quay.io/giantswarm/aws-ebs-csi-volume-limiter
  tag: "0.1.0"
  pullPolicy: IfNotPresent

sidecars:
  provisionerImage:
    repository: quay.io/giantswarm/csi-provisioner
    tag: "v2.1.0"
  attacherImage:
    repository: quay.io/giantswarm/csi-attacher
    tag: "v3.1.0"
  snapshotterImage:
    repository: quay.io/giantswarm/csi-snapshotter
    tag: "v3.0.3"
  livenessProbeImage:
    repository: quay.io/giantswarm/livenessprobe
    tag: "v2.2.0"
  resizerImage:
    repository: quay.io/giantswarm/csi-resizer
    tag: "v1.1.0"
  nodeDriverRegistrarImage:
    repository: quay.io/giantswarm/csi-node-driver-registrar
    tag: "v2.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

# True if enable ebs volume limits per instance type
enableVolumeLimit: true

# True if enable volume scheduling for dynamic volume provisioning
enableVolumeScheduling: true

# True if enable volume resizing
enableVolumeResizing: true

# True if enable volume snapshot
enableVolumeSnapshot: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Extra volume tags to attach to each dynamically provisioned volume.
# ---
# extraVolumeTags:
#   key1: value1
#   key2: value2
extraVolumeTags: {}

# If set, add pv/pvc metadata to plugin create requests as parameters.
extraCreateMetadata: true

# clusterID is dynamic environment value, calculated after cluster creation
# applies only to Giant Swarm clusters
clusterID: "test-cluster"

# AWS region to use. If not specified then the region will be looked up via the AWS EC2 metadata
# service.
# ---
# region: us-east-1
region: ""

node:
  podAnnotations: {}
  tolerations: []

serviceAccount:
  controller:
    annotations: {}
  snapshot:
    annotations: {}
